export default[
    { "_id": "A101", "title": "Propulsion Assignment", "course": "RS101" , "modules": "Modules 1" , "startdate" : "May 6 at 12:00am" , "duedate" : "May 13 at 11:59pm", "untildate" : "July 17 at 12:00am", "points" : "100 pts" , "description" : "Description for Propulsion Assignment"},
    { "_id": "A102", "title": "Combustion Analysis", "course": "RS101" , "modules": "Modules 2" , "startdate" : "May 13 at 12:00am" , "duedate" : "May 20 at 11:59pm", "untildate" : "July 17 at 12:00am", "points" : "50 pts" , "description" : "Description for Combustion Analysis"},
    { "_id": "A103", "title": "Nozzle Design Project", "course": "RS101" , "modules": "Modules 3" , "startdate" : "May 20 at 12:00am" , "duedate" : "May 27 at 11:59pm", "untildate" : "July 17 at 12:00am", "points" : "80 pts" , "description" : "Description for Nozzle Design Project"},
    { "_id": "A201", "title": "Aerodynamics Quiz", "course": "RS102" , "modules": "Modules 1" , "startdate" : "May 6 at 12:00am" , "duedate" : "May 13 at 11:59pm", "untildate" : "July 17 at 12:00am", "points" : "100 pts" , "description" : "Description for Aerodynamics Quiz"},
    { "_id": "A202", "title": "Flow Analysis", "course": "RS102" , "modules": "Modules 2" , "startdate" : "May 13 at 12:00am" , "duedate" : "May 20 at 11:59pm", "untildate" : "July 17 at 12:00am", "points" : "50 pts" , "description" : "Description for Flow Analysis"},
    { "_id": "A203", "title": "Heating Analysis", "course": "RS102" , "modules": "Modules 3" , "startdate" : "May 20 at 12:00am" , "duedate" : "May 27 at 11:59pm", "untildate" : "July 17 at 12:00am", "points" : "80 pts" , "description" : "Description for Heating Analysis"},
    { "_id": "A301", "title": "Structural Design Task", "course": "RS103" , "modules": "Modules 1" , "startdate" : "May 6 at 12:00am" , "duedate" : "May 13 at 11:59pm", "untildate" : "July 17 at 12:00am", "points" : "100 pts" , "description" : "Description for Structural Design Task"},
    { "_id": "A302", "title": "Orbital Calculations", "course": "RS103" , "modules": "Modules 2" , "startdate" : "May 13 at 12:00am" , "duedate" : "May 20 at 11:59pm", "untildate" : "July 17 at 12:00am", "points" : "50 pts" , "description" : "Description for Orbital Calculations"},
    { "_id": "A303", "title": "Systems Engineering Exam", "course": "RS103" , "modules": "Modules 3" , "startdate" : "May 20 at 12:00am" , "duedate" : "May 27 at 11:59pm", "untildate" : "July 17 at 12:00am", "points" : "80 pts" , "description" : "Description for Systems Engineering Exam"}
 ];